[project]
name = "a1personalplanner"
default-app = "web"

[apps.web]
kind = "web-app"
entry-point = "main.jac"

[apps.mobile]
kind = "mobile"
path = "mobile"

[apps.cli]
kind = "cli"
path = "cli"

[serve]
port = 8010

[dependencies.npm]
react-native = "latest"
react-native-web = "latest"
